language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
dist: trusty
sudo: false
addons:
    apt:
        packages:
        - libnotify-bin
        - alsa-utils
        - espeak
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg, Notifier; cd(joinpath(dirname(pathof(Notifier)), "..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg, Notifier; cd(joinpath(dirname(pathof(Notifier)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
