name = "LinuxNotifier"
uuid = "c7071ce2-a4be-4d1f-9307-aaba0b0646ef"
keywords = ["notify", "notification"]
license = "MIT"
desc = "Notification tools for Julialang"
authors = ["goropikari <goropikari56@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
